#!/bin/bash

# iterate through all the files in a directory

for file in /home/cloud_user/*
do
  if [ -d "$file" ]; then
    # enclose the $file variable in double quotation marks
    # to avoid errors generated by space separated names.
    echo "$file is a directory"
  elif [ -f $file ]; then
    echo "$file is a file"
  fi
done
